version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-rest-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n3w0r72fgxov"
s3_prefix = "lambda-rest-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
